apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{ .Release.Name }}
  labels:
    app: myapp
spec:
  replcas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.containers.image_app }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.containers.app_port }}