pipeline {
    agent any

    parameters {
       string( name : 'gitrepo' , defaultValue :  "https://github.com/Shiviell/spring-petclinic.git" ) 
        //dockerCredentials = 'your-docker-credentials-id'  
       string( name: 'imageName' , defaultValue : "petclinic")  // Replace with your Docker image name
        string (name : 'BUILD_NUMBER', defaultValue : "${env.BUILD_NUMBER}")
        string(name : 'branch', defaultValue : "main")
        string(name : 'dockerfile', defaultValue : "spring-petclinic" ) 
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                sh "git clone -b ${branch} ${gitrepo}"
            }
        }

        stage('Build') {
            steps {
                script {
                    // Build Docker image
                    sh "pwd"
                    //sh "cd ${dockerfile}"
                   
                    sh "docker build -f ${dockerfile}/Dockerfile -t shivi2021/${imageName}:${BUILD_NUMBER} ${dockerfile}"
                    }
                }
            }
        

        stage('Test') {
            steps {
                script {
                // Run tests inside the Docker container
                sh "docker run -it -d -p 8080:9080 --name ${imageName} shivi2021/${imageName}:${BUILD_NUMBER}" 
                sh "docker ps"
                sh "docker stop ${imageName}"
                sh "docker rm ${imageName}"
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    // Push Docker image to registry
                    withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                    sh "docker push shivi2021/${imageName}:${BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}
